# Generated by Django 4.2.6 on 2024-02-15 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campusfront', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'verbose_name_plural': 'Buildings'},
        ),
    ]
