# Generated by Django 4.2.6 on 2024-02-15 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campusfront', '0002_alter_building_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={},
        ),
    ]
