# Generated by Django 4.2.6 on 2024-03-19 17:05

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campusfront', '0005_alter_building_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='schoolID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='campusfront.school'),
        ),
        migrations.AddField(
            model_name='school',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326),
        ),
    ]
