# Generated by Django 4.2.6 on 2024-03-30 14:30

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campusfront', '0006_department_schoolid_school_geom'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='office',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='department',
            name='officeID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='campusfront.office'),
        ),
    ]
